const userData = {  
    "results":[  
      {  
        "gender":"male",
        "name":{  
          "title":"mr",
          "first":"jonas",
          "last":"andersen"
        },
        "location":{  
          "street":"9820 grønningen",
          "city":"nimtofte",
          "state":"nordjylland",
          "postcode":32657,
          "coordinates":{  
            "latitude":"-33.6759",
            "longitude":"-129.7589"
          },
          "timezone":{  
            "offset":"+2:00",
            "description":"Kaliningrad, South Africa"
          }
        },
        "email":"jonas.andersen@example.com",
        "dob":{  
          "date":"1952-06-30T09:45:52Z",
          "age":66
        },
        "phone":"55468218",
        "cell":"81513952",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/men/45.jpg",
          "medium":"https://randomuser.me/api/portraits/med/men/45.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/men/45.jpg"
        }
      },
      {  
        "gender":"female",
        "name":{  
          "title":"ms",
          "first":"josefa",
          "last":"rubio"
        },
        "location":{  
          "street":"5776 calle mota",
          "city":"elche",
          "state":"castilla la mancha",
          "postcode":58321,
          "coordinates":{  
            "latitude":"54.1690",
            "longitude":"-115.6998"
          },
          "timezone":{  
            "offset":"+4:30",
            "description":"Kabul"
          }
        },
        "email":"josefa.rubio@example.com",
        "dob":{  
          "date":"1953-04-24T00:35:33Z",
          "age":65
        },
        "phone":"905-771-620",
        "cell":"645-762-501",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/women/84.jpg",
          "medium":"https://randomuser.me/api/portraits/med/women/84.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/women/84.jpg"
        }
      },
      {  
        "gender":"male",
        "name":{  
          "title":"mr",
          "first":"allan",
          "last":"rhodes"
        },
        "location":{  
          "street":"2788 highfield road",
          "city":"bristol",
          "state":"surrey",
          "postcode":"U5 3HW",
          "coordinates":{  
            "latitude":"-1.5916",
            "longitude":"-114.5572"
          },
          "timezone":{  
            "offset":"-3:00",
            "description":"Brazil, Buenos Aires, Georgetown"
          }
        },
        "email":"allan.rhodes@example.com",
        "dob":{  
          "date":"1954-02-28T15:54:42Z",
          "age":64
        },
        "phone":"021 0505 5392",
        "cell":"0791-308-196",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/men/34.jpg",
          "medium":"https://randomuser.me/api/portraits/med/men/34.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/men/34.jpg"
        }
      },
      {  
        "gender":"female",
        "name":{  
          "title":"miss",
          "first":"julia",
          "last":"sutton"
        },
        "location":{  
          "street":"5334 north street",
          "city":"glasgow",
          "state":"wiltshire",
          "postcode":"D4O 3RX",
          "coordinates":{  
            "latitude":"78.9051",
            "longitude":"76.1639"
          },
          "timezone":{  
            "offset":"+2:00",
            "description":"Kaliningrad, South Africa"
          }
        },
        "email":"julia.sutton@example.com",
        "dob":{  
          "date":"1948-04-19T02:55:53Z",
          "age":70
        },
        "phone":"01877 98066",
        "cell":"0797-344-798",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/women/50.jpg",
          "medium":"https://randomuser.me/api/portraits/med/women/50.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/women/50.jpg"
        }
      },
      {  
        "gender":"female",
        "name":{  
          "title":"ms",
          "first":"charly",
          "last":"kortman"
        },
        "location":{  
          "street":"4557 alexander numankade",
          "city":"ede",
          "state":"groningen",
          "postcode":54628,
          "coordinates":{  
            "latitude":"-14.1564",
            "longitude":"159.2812"
          },
          "timezone":{  
            "offset":"-10:00",
            "description":"Hawaii"
          }
        },
        "email":"charly.kortman@example.com",
        "dob":{  
          "date":"1961-12-26T14:35:18Z",
          "age":56
        },
        "phone":"(225)-835-8337",
        "cell":"(951)-632-1195",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/women/14.jpg",
          "medium":"https://randomuser.me/api/portraits/med/women/14.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/women/14.jpg"
        }
      },
      {  
        "gender":"female",
        "name":{  
          "title":"mrs",
          "first":"özsu",
          "last":"yalçın"
        },
        "location":{  
          "street":"5970 doktorlar cd",
          "city":"malatya",
          "state":"giresun",
          "postcode":91582,
          "coordinates":{  
            "latitude":"23.1507",
            "longitude":"-41.5410"
          },
          "timezone":{  
            "offset":"+4:30",
            "description":"Kabul"
          }
        },
        "email":"özsu.yalçın@example.com",
        "dob":{  
          "date":"1979-02-26T07:10:50Z",
          "age":39
        },
        "phone":"(205)-670-3436",
        "cell":"(128)-643-1591",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/women/40.jpg",
          "medium":"https://randomuser.me/api/portraits/med/women/40.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/women/40.jpg"
        }
      },
      {  
        "gender":"male",
        "name":{  
          "title":"mr",
          "first":"henri",
          "last":"pätzold"
        },
        "location":{  
          "street":"gartenstraße 183",
          "city":"zwiesel",
          "state":"brandenburg",
          "postcode":81063,
          "coordinates":{  
            "latitude":"30.3100",
            "longitude":"112.8916"
          },
          "timezone":{  
            "offset":"-2:00",
            "description":"Mid-Atlantic"
          }
        },
        "email":"henri.pätzold@example.com",
        "dob":{  
          "date":"1945-07-25T12:26:11Z",
          "age":73
        },
        "phone":"0986-1950606",
        "cell":"0172-0665720",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/men/59.jpg",
          "medium":"https://randomuser.me/api/portraits/med/men/59.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/men/59.jpg"
        }
      },
      {  
        "gender":"male",
        "name":{  
          "title":"mr",
          "first":"dale",
          "last":"wood"
        },
        "location":{  
          "street":"8168 brick kiln road",
          "city":"peterborough",
          "state":"lincolnshire",
          "postcode":"BZ4Z 7AJ",
          "coordinates":{  
            "latitude":"9.2397",
            "longitude":"30.3223"
          },
          "timezone":{  
            "offset":"+5:30",
            "description":"Bombay, Calcutta, Madras, New Delhi"
          }
        },
        "email":"dale.wood@example.com",
        "dob":{  
          "date":"1991-09-04T17:25:42Z",
          "age":26
        },
        "phone":"015395 08804",
        "cell":"0767-411-998",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/men/70.jpg",
          "medium":"https://randomuser.me/api/portraits/med/men/70.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/men/70.jpg"
        }
      },
      {  
        "gender":"female",
        "name":{  
          "title":"ms",
          "first":"serenity",
          "last":"sanchez"
        },
        "location":{  
          "street":"6197 crockett st",
          "city":"sydney",
          "state":"victoria",
          "postcode":5656,
          "coordinates":{  
            "latitude":"-21.8314",
            "longitude":"111.6812"
          },
          "timezone":{  
            "offset":"+3:30",
            "description":"Tehran"
          }
        },
        "email":"serenity.sanchez@example.com",
        "dob":{  
          "date":"1955-01-08T21:38:50Z",
          "age":63
        },
        "phone":"04-9653-1982",
        "cell":"0481-453-319",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/women/21.jpg",
          "medium":"https://randomuser.me/api/portraits/med/women/21.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/women/21.jpg"
        }
      },
      {  
        "gender":"male",
        "name":{  
          "title":"mr",
          "first":"gökhan",
          "last":"gönültaş"
        },
        "location":{  
          "street":"4348 kushimoto sk",
          "city":"çorum",
          "state":"çanakkale",
          "postcode":17130,
          "coordinates":{  
            "latitude":"54.2266",
            "longitude":"111.0710"
          },
          "timezone":{  
            "offset":"+6:00",
            "description":"Almaty, Dhaka, Colombo"
          }
        },
        "email":"gökhan.gönültaş@example.com",
        "dob":{  
          "date":"1993-03-21T21:43:23Z",
          "age":25
        },
        "phone":"(801)-668-6012",
        "cell":"(677)-554-9325",
        "picture":{  
          "large":"https://randomuser.me/api/portraits/men/86.jpg",
          "medium":"https://randomuser.me/api/portraits/med/men/86.jpg",
          "thumbnail":"https://randomuser.me/api/portraits/thumb/men/86.jpg"
        }
      }
    ]
  }



